# Generated by Django 6.0.7 on 2026-07-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PredictionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_text", models.TextField(verbose_name="Input Text")),
                (
                    "cleaned_text",
                    models.TextField(blank=True, verbose_name="Cleaned Text"),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[("spam", "Spam"), ("ham", "Ham")], max_length=4
                    ),
                ),
                ("confidence", models.FloatField(help_text="Confidence % (0–100)")),
                ("spam_prob", models.FloatField(default=0.0)),
                ("ham_prob", models.FloatField(default=0.0)),
                ("top_keywords", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Prediction",
                "verbose_name_plural": "Prediction History",
                "ordering": ["-created_at"],
            },
        ),
    ]
